name: Feature Request
description: Suggest an improvement to BudgetWise
title: "feat: "
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Feature requests are most helpful when they include a clear user problem and acceptance criteria.
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What user problem are you trying to solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe the smallest viable solution.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
    validations:
      required: false
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      placeholder: |
        - [ ]
        - [ ]
    validations:
      required: true
